### ISSUE TITLE
metal - update prerequisite section for disconnected install for 2.0

### ISSUE THREAD

**Issue by cdoan1** [open-cluster-management/rhacm-docs#1008]
## Product release(s)
- [x] [ACM 2.0 GA] 
- [ ] [ACM 1.0 tech preview]

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 or Sev 1 customer reported bugs for releases in support.

## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* https://github.com/open-cluster-management/rhacm-docs/blob/5fd6fe38ecc502100096ce56b530e81b1b73740b/install/install_disconnected.adoc#install-on-disconnected-networks
*

Section:

* https://github.com/open-cluster-management/rhacm-docs/blob/5fd6fe38ecc502100096ce56b530e81b1b73740b/install/install_disconnected.adoc#prerequisites-for-a-disconnected-installation
*

## What are the suggested changes?

* will submit a PR

**Comment by cdoan1** [comment]
https://github.com/open-cluster-management/rhacm-docs/pull/1014

**Comment by cdoan1** [comment]
@cadawson @dockerymick FYI ^^^

**Comment by swopebe** [comment]
Internal team can open issue in back log, this should be for external users accessing the open repo: https://github.com/open-cluster-management/rhacm-docs/blob/2.0_stage/contributing.adoc

Developers can open issues in backlog as usual. @cadawson looks like dev is sending a PR for this fix but will assign to you.

**Comment by swopebe** [comment]
Can we close this @cadawson ?

**Comment by gghezzo** [comment]
I'm closing it and letting @cdoan1 reopen if needed.
