### ISSUE TITLE
Improvements needed in doc on Channels

### ISSUE THREAD

**Issue by KevinFCormier** [open-cluster-management/rhacm-docs#1055]
## Product release(s)
- [X] [ACM 2.0 GA] 
- [ ] [ACM 1.0 tech preview]

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 or Sev 1 customer reported bugs for releases in support.

## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* manage_applications/managing_channels.adoc

Section:

* Creating and managing channels

## What are the suggested changes?

> Create and use channels when you need to improve the continuous integration and delivery capabilities for creating and managing your Red Hat Advanced Cluster Management for Kubernetes applications.

Do `Red Hat Advanced Cluster Management for Kubernetes applications` have any `continuous integration and delivery capabilities` without the use of channels? This statement seems inaccurate.

> Channels are custom resource definitions that can help you streamline deployments and separate cluster access.
1. `Channel` is a custom resource definition, but I think it's more accurate to say that channels are custom resources.
1. What is meant by "separate cluster access" and why would I want to do that? It's not really clear if this is referring to a user's access to a cluster, or more likely I think, the access that managed clusters have to resources from a channel? The word "separate" is also interesting. Separate from what? Maybe "control" is a more general purpose word.

> Channels (channel.apps.open-cluster-management.io) define a namespace within the hub cluster and point to a physical place where resources are stored for deployment.
1. It's not really clear what is meant by "define a namespace" and an explanation of what that namespace is used for would be helpful. From the new wizard in 2.1, I can see that a channel is a namespace-scoped resource and we use a separate namespace for the channel, but the YAML manually creates this namespace.

> Channels are created on the hub cluster by pointing to the location where resources are stored. Channels are defined with a Channel custom resource definition (CRD). Channels reside in their own namespace for role-based access control.

I believe this should be CR again and not CRD. And it's not clear if all channels should be in 1 namespace or if each channel should reside in its own namespace. Testing it out myself, I confirmed that it is the latter, and that this is actually enforced. So I would suggest "Each channel resides in its own namespace for role-based access control."

**Comment by swopebe** [comment]
Closing--duplicate: **https://github.com/open-cluster-management/backlog/issues/4346**
