### ISSUE TITLE
Subscription docs still use old annotation names

### ISSUE THREAD

**Issue by KevinFCormier** [open-cluster-management/rhacm-docs#1062]
## Product release(s)
- [X] [ACM 2.0 GA] 
- [ ] [ACM 1.0 tech preview]

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 or Sev 1 customer reported bugs for releases in support.

## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* apis/subscriptions.json.adoc
* manage_applications/subscription_sample.adoc

## What are the suggested changes?

See PR: #1061

**Comment by swopebe** [comment]
These should be opened in the backlog like normal, this is for external users. The reason is it cannot get to our board or be seen outside of the doc repo.
