### ISSUE TITLE
Inconsistency in the "creating custom rules" part of the observability documentation

### ISSUE THREAD

**Issue by koep** [open-cluster-management/rhacm-docs#1910]
## Product release(s)
- [x] [ACM 2.2 GA] 

## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* https://github.com/open-cluster-management/rhacm-docs/blob/2.2_prod/observing_environments/customize_observability.adoc#creating-custom-rules

Section:

* Creating custom rules

## What are the suggested changes?

The document says:

```
The key must be named, `thanos-ruler-custom-rules.yaml`, as shown in the following example.
```

But then the example shows:

```
----
data:
  custom_rules.yaml: |
```

Now the question for me, as the reader, is: which is the correct key? `thanos-ruler-custom-rules.yaml` or `custom_rules.yaml`. My tests indicate that `custom_rules.yaml` is the correct key to use.

**Comment by koep** [comment]
There is another issue:

```
Create a ConfigMap named thanos-rule-custom-rules in the open-cluster-management-observability namespace.
```

is supposed to be

```
Create a ConfigMap named thanos-ruler-custom-rules in the open-cluster-management-observability namespace.
```

**Comment by swopebe** [comment]
Actually, closing this and opening on RHACM team backlog.
