### ISSUE TITLE
Network configuration for WorkManager service route 

### ISSUE THREAD

**Issue by hashnao** [open-cluster-management/rhacm-docs#2746]
## Product release(s)
- [ACM 2.3 GA] 

## Locations of the suggested changes?

Links:
* https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html-single/install/index#network-configuration

Section:
* 1.1.3.1. Hub cluster networking requirements
* 1.1.3.2. Managed cluster networking requirements

## What are the suggested changes?
The above sections say "The WorkManager service route on the managed cluster", but for 2.3, there are no exact matches in the route object on the managed cluster as the WorkManager service route in the output below. Probably we want to make it similar to the actual route object name such as the `klusterlet-addon-workmgr` route object in the `open-cluster-management-agent-addon` namespace rather than WorkManager service route, so that we don't have to make a guess.

```
$ oc get -n open-cluster-management-agent-addon route
NAME                       HOST/PORT                                                                                            PATH   SERVICES                   PORT    TERMINATION   WILDCARD
klusterlet-addon-workmgr   klusterlet-addon-workmgr-open-cluster-management-agent-addon.apps.ocp4.49e4.sandbox191.opentlc.com          klusterlet-addon-workmgr   <all>   passthrough   None
```

**Comment by cadawson** [comment]
Hi @ldpliu . Here is a suggestion that was made for the networking content docs for the hub and managed cluster. I think the suggestion is to change `WorkManager`, which is not searchable, to `klusterlet-addon-workmgr`, which is. 

Will you let me know if we should make these changes? Feel free to move it to someone else, if it is better suited for them.  Here is the PR for it: https://github.com/stolostron/rhacm-docs/pull/3130. If it looks ok, then I will backport it to 2.3. Thank you!

Note: This was not opened by someone on our team.

**Comment by ldpliu** [comment]
sure, it's ok for me

**Comment by cadawson** [comment]
This one is updated on staging here: https://dxp-docs.ext.us-west.aws.prod.paas.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html-single/install/index?lb_target=stage#network-configuration-hub. Will be refreshed during our next refresh. Closing this issue..
