### ISSUE TITLE
When using macOS also watch may need to be installed

### ISSUE THREAD

**Issue by tahonen** [open-cluster-management/rhacm-docs#300]
## Product release(s)
- [ x] [ACM 4.4] 

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 & P2 Doc APARS for releases in support.

## Type of documentation change

- [ ] New topic
- [ x] Update to an existing topic

## Link to the topic(s) that require an update

* https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/install/install_connected.md#prerequisites
*

## Draft content or detailed description to get ID started

Content is now:
If you are using macOS, you must install `gsed`. If you do not already have `gsed` installed, you can install it by entering `brew install gnu-sed` in a terminal window.

Should be:
If you are using macOS, you must install `gsed` and `watch`. If you do not already have `gsed` and `watch` installed, you can install it by entering `brew install gnu-sed watch` in a terminal window.

**Comment by cadawson** [comment]
Thanks for this suggestion, Tero. This update has been changed on staging, and will be pushed to production shortly.

**Comment by cadawson** [comment]
Added this to the content.  Optional: If you are using macOS and want to view the progress of your pods starting, you must install watch. If you do not already have watch installed, you can install it by entering brew install watch in a teminal window. You must have watch if you use the --watch option with your installation command. Closing.
