### ISSUE TITLE
Broken link from install/requirements.md to install/hardware_reqs.md (missing)

### ISSUE THREAD

**Issue by BradfordNichols** [open-cluster-management/rhacm-docs#319]
## Product release(s)
- [ ] [ACM 4.4] 

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 & P2 Doc APARS for releases in support.

## Type of documentation change

- [ ] New topic
- [ ] Update to an existing topic

## Link to the topic(s) that require an update

*
*

**Comment by dockerymick** [comment]
@BradfordNichols I have removed the link from the file. It is not present in our repo. Please confirm that the issue can be closed.

**Comment by dockerymick** [comment]
@BradfordNichols Going to move forward and close this. Please reopen if you have other concerns
