### ISSUE TITLE
manage_cluster/import_cli.md step 1 code block is empty

### ISSUE THREAD

**Issue by npoyant** [open-cluster-management/rhacm-docs#320]
https://raw.githubusercontent.com/open-cluster-management/rhacm-docs/doc_prod/manage_cluster/import_cli.md

prep step 1:  empty code block

**Comment by dockerymick** [comment]
@npoyant I have updated the command and will add the link when we refresh our branch.

**Comment by bcpswope** [comment]
This is under construction, it is empty because I need the developer to test and provide. Import CLI was still in progress. @dockerymick I can take this one bc it is linked to an issue/PR I already have out.

**Comment by bcpswope** [comment]
@TheRealHaoLiu and I will get back to you on this, import in the UI has been doc tested, however.

**Comment by bcpswope** [comment]
@TheRealHaoLiu need your help getting this info....flagging waiting for content.

**Comment by bcpswope** [comment]
See https://github.com/open-cluster-management/backlog/issues/1263 for developments. Closed as duplicate, no doc work on this particular issue.
