### ISSUE TITLE
step 3 broken link

### ISSUE THREAD

**Issue by npoyant** [open-cluster-management/rhacm-docs#321]
https://raw.githubusercontent.com/open-cluster-management/rhacm-docs/doc_prod/manage_cluster/import_cli.md

Step 3 Edit the example ClusterRegistry cluster in the /test/resources/test_cluster.yaml file of the open-cluster-management repository

The link in the repository sends it to a location that does not exist

https://github.com/open-cluster-management/rcm-controller/blob/master/test/resources/test_cluster.yaml

**Comment by cadawson** [comment]
Thanks @npoyant .  I think this link might be an internal repo. I am able to access it.  Let me see what I can find out.

**Comment by TheRealHaoLiu** [comment]
the import CLI doc is still work in progress

**Comment by bcpswope** [comment]
I think I should own this issue, as I have taken the other issue and I have an active PR out for @TheRealHaoLiu -- There is "under construction" note at the beginning bc we need to get the PR reviewed. Thanks--I will take this one.

**Comment by bcpswope** [comment]
@TheRealHaoLiu please help with this PR?

https://github.com/open-cluster-management/rhacm-docs/pull/205

This also related to:
 https://github.com/open-cluster-management/rhacm-docs/issues/320

**Comment by bcpswope** [comment]
See https://github.com/open-cluster-management/backlog/issues/1263 for developments. Closed as duplicate, no doc work on this particular issue.
