### ISSUE TITLE
Doc: Install doc needs updated: 4.2 is mentioned install/prep.md, OS topic not updated, etc...

### ISSUE THREAD

**Issue by ch-stark** [open-cluster-management/rhacm-docs#353]
## Product release(s)
- [ ] [ACM 4.4] 

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 & P2 Doc APARS for releases in support.

## Type of documentation change

- [*] New topic

## Link to the topic(s) that require an update
https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/install/prep.md

* This link mentions still to use OpenShift 4.2
* Both from testing experience and from other parts of Docu I assume 4.3 and 4.4 should be necessary

Additionally:

this link:  https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/install/supported_os.md#supported-operating-systems-and-platforms

I believe 3.11 is supported on RHEL 8

OCP 4 is not supported in RHEL 7

**Comment by bcpswope** [comment]
@cadawson I was contacted on Slack, I am also a bit confused about this topic.

**Comment by ch-stark** [comment]
when checking: 
https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/install/install_connected.md
it is mentioned:

See the following prerequisites before installing Red Hat Advanced Cluster Management for Kubernetes:

Red Hat OpenShift Container Platform version 4.3 or 4.4 must be deployed in your environment, and you must be logged into it with the CLI. See the OpenShift version 4.3 documentation or the OpenShift version 4.4 documentation.

**Comment by bcpswope** [comment]
Please see comments here: https://github.com/open-cluster-management/rhacm-docs/pull/355
@cadawson

**Comment by cadawson** [comment]
Thanks @ch-stark . I have made the content consistent in the source, which should be pushed live at some point today.  I noticed that OCP 4.3 is supported on RHEL 7.6, and later, according to the following topic: https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-installation-and-upgrade .  Let me know if there is something that I missed.

**Comment by bcpswope** [comment]
@cadawson can we close?

**Comment by cadawson** [comment]
Closing this issue.
