### ISSUE TITLE
Remove Overview page for GRC 

### ISSUE THREAD

**Issue by dockerymick** [open-cluster-management/rhacm-docs#358]
## Product release(s)
- [ ] [ACM 4.4] 

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 & P2 Doc APARS for releases in support.

## Type of documentation change

- [ ] New topic
- [ ] Update to an existing topic

## Link to the topic(s) that require an update

* https://coreos.slack.com/archives/GUQS3CS5A/p1586367959097700
* https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/governance/compliance_intro.md
* https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/console/console.md

**Comment by therealljrodrig** [comment]
@dockerymick Can I get guidance on how I can help so we're not both doing the same things? :)

**Comment by dockerymick** [comment]
@therealljrodrig so far I have scanned the rhacm-docs repo to find instances, where I explained the functionality and benefits of the Overview page. I found only 2 files and they should be easy fixes. May you review my PR once i create it?

**Comment by therealljrodrig** [comment]
@dockerymick I'm relieved to hear it wasn't more disruptive.

**Comment by dockerymick** [comment]
Here is the PR: https://github.com/open-cluster-management/rhacm-docs/pull/362 

I made a comment on line 51 of the console/console.md file. Will the users be able to view the details in another location, even though it is not on the Overview page?

**Comment by dockerymick** [comment]
I have removed mentions of security risks @therealljrodrig are you ok with us closing the issue?

**Comment by therealljrodrig** [comment]
good with me @dockerymick
