### ISSUE TITLE
Doc how users can access image vulnerability violations

### ISSUE THREAD

**Issue by dockerymick** [open-cluster-management/rhacm-docs#370]
## Product release(s)
- [ ] [ACM 4.4] 

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 & P2 Doc APARS for releases in support.

## Type of documentation change

- [x] New topic
- [ ] Update to an existing topic

## Link to the topic(s) that require an update

*
*

## Draft content or detailed description to get ID started

Reorganize your dashboard. You can personalize your view of the Overview dashboard by reorganizing the resource overview cards. You can view the following information about your clusters:

**Comment by ycao56** [comment]
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/16092291/78932975-7bcd4080-7a76-11ea-8b3c-ce139cc924f4.png">

Violation looks like above
```
magemanifestvulns exist and should be deleted: [sha256.7ac7819e1523911399b798309025935a9968b277d86d50e5255465d6592c0266] in namespace default; [sha256.4109631e69d1d562f014dd49d5166f1c18b4093f4f311275236b94b21c0041c0] in namespace calamari; [sha256.573e9e0a1198da4e29eb9a8d7757f7afb7ad085b0771bc6aa03ef96dedc5b743, sha256.a56d40244a544693ae18178a0be8af76602b89abe146a43613eaeac84a27494e, sha256.b25126b194016e84c04a64a0ad5094a90555d70b4761d38525e4aed21d372820] in namespace multicluster-endpoint; [sha256.64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a] in namespace openshift-cluster-version
```

`[sha256.7ac7819e1523911399b798309025935a9968b277d86d50e5255465d6592c0266] in namespace default`
We list object name by namespace.
1. User then can click on the `cluster` link and go to OCP console for that managed cluster.
2. On OCP console left nav, click `Administration` to expand and then click `Custom Resource Definitions`
3. In the list, find `imagemanifestvulns` and click
4. Then click on `Instances` tab to see all the `imagemanifestvulns` instances

**Comment by dockerymick** [comment]
@willkutler Awesome job with your demo today! May you help me produce the doc by reviewing my PR? I will create a document explaining what an Image vulnerability policy is, why is should be created, and how it can be created and edited. I also think it would be beneficial to add a note about the namespace override.

**Comment by willkutler** [comment]
@dockerymick sure, just add me as a reviewer when it's done! The namespace override will happen in the policy controller in general

**Comment by dockerymick** [comment]
@willkutler Thanks so much!

**Comment by dockerymick** [comment]
https://github.com/open-cluster-management/backlog/issues/1317

**Comment by dockerymick** [comment]
@ycao56 @willkutler I have added the note here: https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/security/policy_example.md

And instructions to view image vulnerability violations here: https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/security/create_image_vuln.md

You all ok with closing the issue?

**Comment by willkutler** [comment]
@dockerymick looks good to me!

**Comment by drkho** [comment]
@dockerymick Hi, does this issue make it into 1.0 or 2.0 documentation? If so, would you please provide the current link here and in the https://bugzilla.redhat.com/show_bug.cgi?id=1822684. Thanks.

**Comment by dockerymick** [comment]
@drkho sure thing, I will add the links there. I would also like to add them here. Here is the link for [Managing image vulnerability policies for 1.0](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/1.0/html/security/security#managing-image-vulnerability-policies) and the [2.0 link](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.0/html/security/security#managing-image-vulnerability-policies)

I also added the following note: "Note: A namespace that is specified in the object template of a policy controller overrides the namespace in the corresponding parent policy."

in the [1.3.1.2. Policy YAML table for 1.0](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/1.0/html/security/security#governance-and-risk), and [2.0 link](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.0/html/security/security#policy-overview)
