### ISSUE TITLE
[Doc] Add section about supported cable drivers for Submariner

### ISSUE THREAD

**Issue by manosnoam** [open-cluster-management/rhacm-docs#4145]
Currently we have in the [Docs](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html-single/release_notes/index#submariner-vxlan) some troubleshooting about VxLAN for Submariner, but we should rather have a seperate section about all supported cable drivers.

For example, it should cover info about VxLAN as unencrypted connection - i.e. it is not advised to be used within pubic clouds, but only in an on-prem network.

_Originally posted by @manosnoam in https://github.com/submariner-io/submariner-website/issues/799#issuecomment-1259862124_

**Comment by manosnoam** [comment]
FYI @dfarrell07 do you want to add it to 2.7 backlog ?

**Comment by oafischer** [comment]
@manosnoam Please use the correct template and procedures to create doc issues. See here: https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit#heading=h.9fvyr2rdriby

**Comment by manosnoam** [comment]
> @manosnoam Please use the correct template and procedures to create doc issues. See here: https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit#heading=h.9fvyr2rdriby

@oafischer, I guess you meant to add "Portal doc issue" from here: https://github.com/stolostron/backlog/issues/new/choose

**Comment by oafischer** [comment]
@manosnoam The link I sent is correct. It walks you through the correct process and also includes the link to the template.

**Comment by manosnoam** [comment]
Closing this issue, in favor of this: https://github.com/stolostron/backlog/issues/26135
