### ISSUE TITLE
missing --base-domain

### ISSUE THREAD

**Issue by jwilms1971** [open-cluster-management/rhacm-docs#4634]
### **THIS IS FOR EXTERNAL CUSTOMERS ONLY!**

Red Hatters please open issues in the [developer backlog](https://github.com/stolostron/backlog/issues/new/choose), or BugZilla if you are not an authorized user for the backlog.

**Note:** Doc team will update the current version and the two previous versions (n-2). For earlier versions, we will address only Sev 1, customer-reported bugs for releases in support.

## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

*
*

Section:

*
*

## What are the suggested changes?

Missing --base-domain flag for the command hypershift create cluster aws command.

Also the value of AWS_CREDS is ambigous. Probably should be $HOME/.aws/credentials and not $HOME/name-aws

**Comment by swopebe** [comment]
I will look into this. Additionally, we need to change this so that issues are opened in JIRA since the team is not using this workspace.

**Comment by rokej** [comment]
hcp create cluster aws --help
hypershift create cluster aws --help

I see the flags with clear description. 

```
--aws-creds string             Path to an AWS credentials file (required)
--base-domain string                         The ingress base domain for the cluster
```

**Comment by swopebe** [comment]
Closed given the age, the location of the issue, and the work done since. 

Please open further issues in JIRA.
