### ISSUE TITLE
Consider changing kubectl references to oc

### ISSUE THREAD

**Issue by atgreen** [open-cluster-management/rhacm-docs#480]
The instructions for preparing the hub cluster include kubectl commands.   Consider changing those to oc commands, as the hub cluster must be OpenShift, and OCP admins will definitely have 'oc'.  As far as I know, Red Hat does not provide a supported kubectl.

**Comment by bcpswope** [comment]
Hi.. we have an issue already opened. We cannot change the doc unless the dev team has this function tested. https://github.com/open-cluster-management/backlog/issues/1412

**Comment by bcpswope** [comment]
Can we close this issue? It is the only one in our specific repo, most are opening in backlog as usual... see above comment, this is a duplicate and labeled as such.
