### ISSUE TITLE
objects use invalid date in version that does not work

### ISSUE THREAD

**Issue by bryan-croft** [open-cluster-management/rhacm-docs#6142]
## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* https://github.com/stolostron/rhacm-docs/blob/2.10_stage/observability/observability_enable.adoc

Section:

* https://github.com/stolostron/rhacm-docs/blob/2.10_stage/observability/observability_enable.adoc#generating-access-keys-using-the-aws-security-service

## What are the suggested changes?

The script in step one of that section produces invalid objects, and if followed, the configuration **will fail**. Specifically, it sets the following to the current date:

```bash
export POLICY_VERSION=$(date +"%m-%d-%y")
export TRUST_POLICY_VERSION=$(date +"%m-%d-%y")
```

Those are then referenced as the values for the object's `Version` in later steps. The `Version` field is actually the date corresponding to when the schema was introduced, per: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_version.html

When I tested configuration following the documented steps, the objects failed to create on the AWS side because the current date is not a valid value. The correct value should be `2012-10-17` and when I hardcoded that value in the JSON, it worked.

**Comment by swopebe** [comment]
@bryan-croft TY for this.

We have in the contributing guide a link to JIRA, as the product team is no longer working in GH. I see you are on Slack, so I will connect you to the dev team.

Any bugs regarding the code need to go through development before we would update the doc. So I will close this, as it is not a doc bug, and send your contact via a JIRA to the dev team.

2.10 is not published, so keep that in mind. 2.9 is the current published doc. 
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/observability/index

**Comment by swopebe** [comment]
JIRA issue sent to obs. team, but I want to stress that 2.10 is not published for use: https://issues.redhat.com/browse/ACM-10061

**Comment by bryan-croft** [comment]
The same mistake has been present in the docs since those instructions were added. I linked the 2.10 docs, but 2.9 is broken, 2.8 is broken, etc.

I get that you need development to review, but the current published *docs are wrong* and if you follow their instructions exactly, it *will not work*, so saying: " it is not a doc bug" seems wrong to me. What are issues even for in this repo if they are not used to note problems with the docs?

**Comment by swopebe** [comment]
This is a code bug if the procedure that is written, which is from the engineering team, does not work. I cannot test the procedure. A doc bug would be something that I can test and fix, so I sent this to the development team.

**Comment by swopebe** [comment]
Reached out to Moab for the doc change.

**Comment by bryan-croft** [comment]
Thanks for taking time to explain the distinction between code and doc changes. Thanks for reaching out to the appropriate team.
