### ISSUE TITLE
OCP installation misleading

### ISSUE THREAD

**Issue by VinayBhalerao** [open-cluster-management/rhacm-docs#768]
https://github.com/open-cluster-management/rhacm-docs/blob/d161126c7fc25f51066b2afe96d086ce219841c5/install/install_overview.md

```You must have a supported version of OpenShift Container Platform installed on premise.```

I think `on premise` it's kind of misleading. You can have OCP installed on premise or any cloud provider. Both points (1) and (2) need to be well corrected.

**Comment by cadawson** [comment]
This is updated and merged. Closing it, but open a new issue, if there is something additionally that is needed.  Thank you!
