### ISSUE TITLE
Update the folder name to match book names

### ISSUE THREAD

**Issue by dockerymick** [open-cluster-management/rhacm-docs#981]
## Product release(s)
- [x] [ACM 2.0 GA] 
- [ ] [ACM 1.0 tech preview]

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 or Sev 1 customer reported bugs for releases in support.

## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* https://github.com/open-cluster-management/rhacm-docs/blob/2.0_stage/troubleshoot_acm/master.adoc
*

Section:

*
*

## What are the suggested changes?

Let's update the folder name troubleshoot_acm to troubleshooting, to match the book title. This will help with consistencies in the URL path.  update links and xrefs `link:../troubleshoot_acm/file_name.adoc` to `link:../troubleshooting/acm.adoc`

I also would recommend that we update the troubleshooting.adoc filename to troubleshooting_intro.adoc 

https://github.com/open-cluster-management/backlog/issues/3554

**Comment by dockerymick** [comment]
I will close the issue when the URL for the stage environment updates.

**Comment by swopebe** [comment]
We are published. Think we can close.
